### ISSUE TITLE
Some offerings

### ISSUE THREAD

**Issue by Ekey** [GoneUp/Tera_PacketViewer#1]
1)
useless part of code

```
    public byte[] ServerKey1 = Utils.Random128Key();
    public byte[] ServerKey2 = Utils.Random128Key();
```

replace on

```
    public byte[] ServerKey1 = new byte[128];
    public byte[] ServerKey2 = new byte[128];
```

because ServerKey1 and ServerKey2 filled anyway from 

```
    public bool ProcessServerData()
```

2)

Can you add loading servers list from xml config? Like this http://pastebin.com/U8cf34Lm

**Comment by GoneUp** [comment]
to 1) Yep, it's pretty useless in our Case. It just from the historical funtion of the code. It was a encryption class for a emulator, so it pregenerated the serverkey.

to 2) Yep, it's possible to add that optinally. Can you provide a xml file I can work with?

**Comment by Ekey** [comment]
Yeah sure.. Here collected ip's : 
v1 - http://pastebin.com/5PtcZbbF

Also after ip could be added tag for loading individual opcode list for each regions.
v2 - http://pastebin.com/c4heg6yM

:)

**Comment by GoneUp** [comment]
Included
