### ISSUE TITLE
Loading connection logs

### ISSUE THREAD

**Issue by gothos-folly** [GoneUp/Tera_PacketViewer#2]
It'd be nice if your packet viewer could load the logs produced by my sniffer.

Format specification: [TeraConnectionLog Specification.md](https://github.com/gothos-folly/TeraDamageMeter/blob/master/TeraConnectionLog%20Specification.md)

For minimal support you only need to handle _server_ and _client_ blocks. Parsing them should be easy, since you can already parse Tera messages, which have a pretty similar format.

**Comment by GoneUp** [comment]
Sure, that should be no problem. Gonna add it during the week.

**Comment by GoneUp** [comment]
Okay, added it. Try it please.
Oh, the download is here in a fancy release download page https://github.com/GoneUp/Tera_PacketViewer/releases
First saw the function on your meter, very usefull:D

**Comment by gothos-folly** [comment]
It works. Thanks for adding it.

**Comment by GoneUp** [comment]
Great ^^
