### ISSUE TITLE
Exception on startup

### ISSUE THREAD

**Issue by VenoMKO** [GoneUp/Tera_PacketViewer#4]
Win7x64 (RU local) winpcap installed
Screenshot: [http://i.imgur.com/sVG3KY7.png](http://i.imgur.com/sVG3KY7.png)

**Comment by GoneUp** [comment]
Can you try to put the dlls included in v6 in a folder together with the v7 exe?

**Comment by VenoMKO** [comment]
Same issue. Actually i tried to run v6 and got the same error. On Win10 v6 worked fine.

**Comment by GoneUp** [comment]
According to Google something is wrong with your machine. It should help to delete .Net framework and reinstall it. 

https://www.microsoft.com/de-de/download/details.aspx?id=49981

**Comment by VenoMKO** [comment]
Yep this did the trick, thanks! You may close the issue now.
Btw is there any way to save packet log to a file (txt, xml or raw bytes)?

**Comment by GoneUp** [comment]
Nice ^^
In the actual version there is no logging functionality. I gonna add that next week when I'm back from vacation.

**Comment by VenoMKO** [comment]
Ok, thanks! Will keep an eye on the repo!
