### ISSUE TITLE
one qustion plz

### ISSUE THREAD

**Issue by MrxD77** [GoneUp/Tera_PacketViewer#8]
is ur code work in psn ?

**Comment by GoneUp** [comment]
What is psn?

**Comment by MrxD77** [comment]
playstation 
or can we contact in skype i won to make one program i have the source only u make it 
if u make i will pay to u

**Comment by GoneUp** [comment]
Lol. This program is only for Tera on a pc. 
Can you give me a short description what the task would be?

**Comment by MrxD77** [comment]
i will explan to u in skype can u add me

**Comment by GoneUp** [comment]
Okay, add me. Addy is GoneUp2

**Comment by MrxD77** [comment]
OKAY DONE
