### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by ghost** [GoneUp/Tera_PacketViewer#9]
Hello, can you make update for this tool for the new version of Tera ?

I tried but doen't work.

Ty

**Comment by GoneUp** [comment]
Sorry, not really. The packet encryption changed and the old way to export opcodes does not work anymore. I suggest you look this like tera-proxy or tera-toolbox. They are actual and provide logging mods. 
https://github.com/tera-toolbox/tera-toolbox
